.TH "C:/Users/Madimetja/Documents/GitHub/bravo/FinancialMarketSimulator/src/financialmarketsimulator/receipts Directory Reference" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Madimetja/Documents/GitHub/bravo/FinancialMarketSimulator/src/financialmarketsimulator/receipts Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBidReceipt\&.java\fP"
.br
.ti -1c
.RI "file \fBOfferReceipt\&.java\fP"
.br
.ti -1c
.RI "file \fBReceipt\&.java\fP"
.br
.ti -1c
.RI "file \fBTradeReceipt\&.java\fP"
.br
.in -1c
