.TH "ExchangeUnitTest" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExchangeUnitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExchangeUnitTest\fP ()"
.br
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBinstantiation\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 21 of file ExchangeUnitTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExchangeUnitTest\&.ExchangeUnitTest ()"

.PP
Definition at line 23 of file ExchangeUnitTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ExchangeUnitTest\&.instantiation ()"

.PP
Definition at line 53 of file ExchangeUnitTest\&.java\&.
.SS "void ExchangeUnitTest\&.setUp ()"

.PP
Definition at line 35 of file ExchangeUnitTest\&.java\&.
.SS "static void ExchangeUnitTest\&.setUpClass ()\fC [static]\fP"

.PP
Definition at line 27 of file ExchangeUnitTest\&.java\&.
.SS "void ExchangeUnitTest\&.tearDown ()"

.PP
Definition at line 39 of file ExchangeUnitTest\&.java\&.
.SS "static void ExchangeUnitTest\&.tearDownClass ()\fC [static]\fP"

.PP
Definition at line 31 of file ExchangeUnitTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
