.TH "financialmarketsimulator.receipts.BidReceipt" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.receipts.BidReceipt \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfinancialmarketsimulator\&.receipts\&.Receipt\fP\&.
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Moeletji 
.RE
.PP

.PP
Definition at line 13 of file BidReceipt\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
