.TH "financialmarketsimulator" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBreceipts\fP"
.br
.ti -1c
.RI "package \fBstack\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBid\fP"
.br
.ti -1c
.RI "class \fBFinancialMarketSimulator\fP"
.br
.ti -1c
.RI "class \fBMarketEntity\fP"
.br
.ti -1c
.RI "class \fBMarketEntryAttempt\fP"
.br
.ti -1c
.RI "class \fBMarketManager\fP"
.br
.ti -1c
.RI "class \fBMarketStrategy\fP"
.br
.ti -1c
.RI "class \fBMatchingEngine\fP"
.br
.ti -1c
.RI "class \fBOffer\fP"
.br
.ti -1c
.RI "interface \fBTrade\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
