.TH "financialmarketsimulator.stack.MarketEntryAttemptNode" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.stack.MarketEntryAttemptNode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarketEntryAttemptNode\fP (\fBMarketEntryAttempt\fP node1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBnext\fP"
.br
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 14 of file MarketEntryAttemptNode\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "financialmarketsimulator\&.stack\&.MarketEntryAttemptNode\&.MarketEntryAttemptNode (\fBMarketEntryAttempt\fPnode1)"

.PP
Definition at line 19 of file MarketEntryAttemptNode\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.stack\&.MarketEntryAttemptNode\&.next"

.PP
Definition at line 16 of file MarketEntryAttemptNode\&.java\&.
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.stack\&.MarketEntryAttemptNode\&.node"

.PP
Definition at line 17 of file MarketEntryAttemptNode\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
