.TH "financialmarketsimulator.FinancialMarketSimulator" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.FinancialMarketSimulator \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Madimetja Shika, Moeletji Semenya, Daniel Makgonta 
.RE
.PP

.PP
Definition at line 8 of file FinancialMarketSimulator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void financialmarketsimulator\&.FinancialMarketSimulator\&.main (String[]args)\fC [static]\fP"

.PP
Definition at line 10 of file FinancialMarketSimulator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
