.TH "financialmarketsimulator.stack.MarketEntryAttemptNode" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.stack.MarketEntryAttemptNode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarketEntryAttemptNode\fP (\fBMarketEntryAttempt\fP node1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBnext\fP"
.br
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 14 of file MarketEntryAttemptNode\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
