.TH "financialmarketsimulator.MarketStrategy" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.MarketStrategy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfinancialmarketsimulator\&.Trade\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBmakeOffer\fP ()"
.br
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBmakeBid\fP ()"
.br
.ti -1c
.RI "void \fBretractBid\fP ()"
.br
.ti -1c
.RI "void \fBretractOffer\fP ()"
.br
.ti -1c
.RI "void \fBsetStrategy\fP (String strategy)"
.br
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBsearchMarketEntryAttempt\fP (\fBMarketEntryAttempt\fP entry)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 12 of file MarketStrategy\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.MarketStrategy\&.makeBid ()"

.PP
Implements \fBfinancialmarketsimulator\&.Trade\fP\&.
.PP
Definition at line 19 of file MarketStrategy\&.java\&.
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.MarketStrategy\&.makeOffer ()"

.PP
Implements \fBfinancialmarketsimulator\&.Trade\fP\&.
.PP
Definition at line 15 of file MarketStrategy\&.java\&.
.SS "void financialmarketsimulator\&.MarketStrategy\&.retractBid ()"

.PP
Implements \fBfinancialmarketsimulator\&.Trade\fP\&.
.PP
Definition at line 23 of file MarketStrategy\&.java\&.
.SS "void financialmarketsimulator\&.MarketStrategy\&.retractOffer ()"

.PP
Implements \fBfinancialmarketsimulator\&.Trade\fP\&.
.PP
Definition at line 27 of file MarketStrategy\&.java\&.
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.MarketStrategy\&.searchMarketEntryAttempt (\fBMarketEntryAttempt\fPentry)"

.PP
Implements \fBfinancialmarketsimulator\&.Trade\fP\&.
.PP
Definition at line 35 of file MarketStrategy\&.java\&.
.SS "void financialmarketsimulator\&.MarketStrategy\&.setStrategy (Stringstrategy)"

.PP
Implements \fBfinancialmarketsimulator\&.Trade\fP\&.
.PP
Definition at line 31 of file MarketStrategy\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
