.TH "financialmarketsimulator.MatchingEngine" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.MatchingEngine \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchingEngine\fP ()"
.br
.ti -1c
.RI "void \fBtrade\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Madimetja Shika, Moeletji Semenya, Daniel Makgonta 
.RE
.PP

.PP
Definition at line 7 of file MatchingEngine\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "financialmarketsimulator\&.MatchingEngine\&.MatchingEngine ()"

.PP
Definition at line 9 of file MatchingEngine\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void financialmarketsimulator\&.MatchingEngine\&.trade ()"

.PP
Definition at line 14 of file MatchingEngine\&.java\&.
.SS "void financialmarketsimulator\&.MatchingEngine\&.update ()"

.PP
Definition at line 19 of file MatchingEngine\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
