.TH "financialmarketsimulator.receipts" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.receipts \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBidReceipt\fP"
.br
.ti -1c
.RI "class \fBOfferReceipt\fP"
.br
.ti -1c
.RI "class \fBReceipt\fP"
.br
.ti -1c
.RI "class \fBTradeReceipt\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
