.TH "financialmarketsimulator.stack.Stack" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.stack.Stack \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBfinancialmarketsimulator\&.stack\&.BidStack\fP, and \fBfinancialmarketsimulator\&.stack\&.OfferStack\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP (\fBMarketEntryAttemptNode\fP node)  throws InterruptedException "
.br
.ti -1c
.RI "\fBMarketEntryAttemptNode\fP \fBpop\fP ()  throws EmptyException, InterruptedException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBtryPush\fP (\fBMarketEntryAttemptNode\fP node)"
.br
.ti -1c
.RI "\fBMarketEntryAttemptNode\fP \fBtryPop\fP ()  throws EmptyException "
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 15 of file Stack\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
