.TH "financialmarketsimulator.Trade" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.Trade \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBfinancialmarketsimulator\&.MarketStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBmakeOffer\fP ()"
.br
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBmakeBid\fP ()"
.br
.ti -1c
.RI "void \fBretractBid\fP ()"
.br
.ti -1c
.RI "void \fBretractOffer\fP ()"
.br
.ti -1c
.RI "void \fBsetStrategy\fP (String strategy)"
.br
.ti -1c
.RI "\fBMarketEntryAttempt\fP \fBsearchMarketEntryAttempt\fP (\fBMarketEntryAttempt\fP entry)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 12 of file Trade\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.Trade\&.makeBid ()"

.PP
Implemented in \fBfinancialmarketsimulator\&.MarketStrategy\fP\&.
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.Trade\&.makeOffer ()"

.PP
Implemented in \fBfinancialmarketsimulator\&.MarketStrategy\fP\&.
.SS "void financialmarketsimulator\&.Trade\&.retractBid ()"

.PP
Implemented in \fBfinancialmarketsimulator\&.MarketStrategy\fP\&.
.SS "void financialmarketsimulator\&.Trade\&.retractOffer ()"

.PP
Implemented in \fBfinancialmarketsimulator\&.MarketStrategy\fP\&.
.SS "\fBMarketEntryAttempt\fP financialmarketsimulator\&.Trade\&.searchMarketEntryAttempt (\fBMarketEntryAttempt\fPentry)"

.PP
Implemented in \fBfinancialmarketsimulator\&.MarketStrategy\fP\&.
.SS "void financialmarketsimulator\&.Trade\&.setStrategy (Stringstrategy)"

.PP
Implemented in \fBfinancialmarketsimulator\&.MarketStrategy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
