.TH "financialmarketsimulator.MarketManager" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.MarketManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarketManager\fP ()"
.br
.ti -1c
.RI "\fBMarketManager\fP (String sName, String sType, int numShares, double val)"
.br
.ti -1c
.RI "String \fBacceptBid\fP (\fBBid\fP bid)"
.br
.ti -1c
.RI "String \fBacceptOffer\fP (\fBOffer\fP offer)"
.br
.ti -1c
.RI "String \fBremoveBid\fP (\fBBid\fP bid)"
.br
.ti -1c
.RI "String \fBremoveOffer\fP (\fBOffer\fP offer)"
.br
.ti -1c
.RI "void \fBupdateEngine\fP ()"
.br
.ti -1c
.RI "void \fBupdateEntities\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Madimetja Shika, Moeletji Semenya, Daniel Makgonta 
.RE
.PP

.PP
Definition at line 10 of file MarketManager\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "financialmarketsimulator\&.MarketManager\&.MarketManager ()"

.PP
Definition at line 21 of file MarketManager\&.java\&.
.SS "financialmarketsimulator\&.MarketManager\&.MarketManager (StringsName, StringsType, intnumShares, doubleval)"

.PP
Definition at line 25 of file MarketManager\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String financialmarketsimulator\&.MarketManager\&.acceptBid (\fBBid\fPbid)"

.PP
Definition at line 35 of file MarketManager\&.java\&.
.SS "String financialmarketsimulator\&.MarketManager\&.acceptOffer (\fBOffer\fPoffer)"

.PP
Definition at line 40 of file MarketManager\&.java\&.
.SS "String financialmarketsimulator\&.MarketManager\&.removeBid (\fBBid\fPbid)"

.PP
Definition at line 45 of file MarketManager\&.java\&.
.SS "String financialmarketsimulator\&.MarketManager\&.removeOffer (\fBOffer\fPoffer)"

.PP
Definition at line 50 of file MarketManager\&.java\&.
.SS "void financialmarketsimulator\&.MarketManager\&.updateEngine ()"

.PP
Definition at line 54 of file MarketManager\&.java\&.
.SS "void financialmarketsimulator\&.MarketManager\&.updateEntities ()"

.PP
Definition at line 58 of file MarketManager\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
