.TH "financialmarketsimulator.Offer" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.Offer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfinancialmarketsimulator\&.MarketEntryAttempt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOffer\fP ()"
.br
.ti -1c
.RI "\fBOffer\fP (double _price, int _numShares, String _name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Madimetja Shika, Moeletji Semenya, Daniel Makgonta 
.RE
.PP

.PP
Definition at line 9 of file Offer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "financialmarketsimulator\&.Offer\&.Offer ()"

.PP
Definition at line 11 of file Offer\&.java\&.
.SS "financialmarketsimulator\&.Offer\&.Offer (double_price, int_numShares, String_name)"

.PP
Definition at line 16 of file Offer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
