.TH "financialmarketsimulator.MarketManager" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.MarketManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarketManager\fP ()"
.br
.ti -1c
.RI "\fBMarketManager\fP (String sName, String sType, int numShares, double val)"
.br
.ti -1c
.RI "\fBReceipt\fP \fBacceptBid\fP (\fBBid\fP bid)"
.br
.ti -1c
.RI "\fBReceipt\fP \fBacceptOffer\fP (\fBOffer\fP offer)"
.br
.ti -1c
.RI "String \fBremoveBid\fP (\fBBid\fP bid)"
.br
.ti -1c
.RI "String \fBremoveOffer\fP (\fBOffer\fP offer)"
.br
.ti -1c
.RI "void \fBupdateEngine\fP ()"
.br
.ti -1c
.RI "void \fBupdateEntities\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Madimetja Shika, Moeletji Semenya, Daniel Makgonta 
.RE
.PP

.PP
Definition at line 11 of file MarketManager\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "financialmarketsimulator\&.MarketManager\&.MarketManager ()"
\fBMarketManager\fP Constructor 
.PP
Definition at line 24 of file MarketManager\&.java\&.
.SS "financialmarketsimulator\&.MarketManager\&.MarketManager (StringsName, StringsType, intnumShares, doubleval)"
\fBMarketManager\fP Constructor
.PP
\fBParameters:\fP
.RS 4
\fIsName\fP Name of the stock 
.br
\fIsType\fP Type of stock 
.br
\fInumShares\fP Number of shares the stock holds 
.br
\fIval\fP Market value of the stock 
.RE
.PP

.PP
Definition at line 36 of file MarketManager\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBReceipt\fP financialmarketsimulator\&.MarketManager\&.acceptBid (\fBBid\fPbid)"

.PP
\fBTodo\fP
.RS 4
Acknowledgement of the bid being accepted by the market manager 
.PP
\fBParameters:\fP
.RS 4
\fIbid\fP \fBBid\fP object to be accepted 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns a receipt object that acknowledges that a bid was accepted 
.RE
.PP
.RE
.PP

.PP
Definition at line 50 of file MarketManager\&.java\&.
.SS "\fBReceipt\fP financialmarketsimulator\&.MarketManager\&.acceptOffer (\fBOffer\fPoffer)"

.PP
\fBTodo\fP
.RS 4
Acknowledgement of the offer being accepted by the market manager
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIoffer\fP \fBOffer\fP object to be accepted 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns a receipt object that acknowledges that an offer was accepted 
.RE
.PP

.PP
Definition at line 60 of file MarketManager\&.java\&.
.SS "String financialmarketsimulator\&.MarketManager\&.removeBid (\fBBid\fPbid)"

.PP
\fBTodo\fP
.RS 4
Acknowledgement of the bid being removed by the market manager
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIbid\fP \fBBid\fP to be removed 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns a receipt object that acknowledges that an offer was removed 
.RE
.PP

.PP
Definition at line 70 of file MarketManager\&.java\&.
.SS "String financialmarketsimulator\&.MarketManager\&.removeOffer (\fBOffer\fPoffer)"

.PP
\fBTodo\fP
.RS 4
Acknowledgement of the offer being removed by the market manager
.RE
.PP
.PP
\fBParameters:\fP
.RS 4
\fIbid\fP \fBOffer\fP to be removed 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns a receipt object that acknowledges that an offer was removed 
.RE
.PP

.PP
Definition at line 80 of file MarketManager\&.java\&.
.SS "void financialmarketsimulator\&.MarketManager\&.updateEngine ()"

.PP
\fBTodo\fP
.RS 4
Update the engine with the current states of the bid and offer stack\&. 
.RE
.PP

.PP
Definition at line 87 of file MarketManager\&.java\&.
.SS "void financialmarketsimulator\&.MarketManager\&.updateEntities ()"

.PP
\fBTodo\fP
.RS 4
Update entities 
.RE
.PP

.PP
Definition at line 94 of file MarketManager\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
