.TH "financialmarketsimulator.stack.Backoff" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.stack.Backoff \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackoff\fP (int min, int max)"
.br
.ti -1c
.RI "void \fBbackoff\fP ()  throws InterruptedException "
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 15 of file Backoff\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "financialmarketsimulator\&.stack\&.Backoff\&.Backoff (intmin, intmax)"

.PP
Definition at line 21 of file Backoff\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void financialmarketsimulator\&.stack\&.Backoff\&.backoff () throws InterruptedException"

.PP
Definition at line 28 of file Backoff\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
