.TH "financialmarketsimulator.Bid" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.Bid \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBfinancialmarketsimulator\&.MarketEntryAttempt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBid\fP (double _price, int _numShares, String _name)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Madimetja Shika, Moeletji Semenya, Daniel Makgonta 
.RE
.PP

.PP
Definition at line 9 of file Bid\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
