.TH "financialmarketsimulator.stack.Stack" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
financialmarketsimulator.stack.Stack \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBfinancialmarketsimulator\&.stack\&.BidStack\fP, and \fBfinancialmarketsimulator\&.stack\&.OfferStack\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush\fP (\fBMarketEntryAttemptNode\fP node)  throws InterruptedException "
.br
.ti -1c
.RI "\fBMarketEntryAttemptNode\fP \fBpop\fP ()  throws EmptyException, InterruptedException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBtryPush\fP (\fBMarketEntryAttemptNode\fP node)"
.br
.ti -1c
.RI "\fBMarketEntryAttemptNode\fP \fBtryPop\fP ()  throws EmptyException "
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 14 of file Stack\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMarketEntryAttemptNode\fP financialmarketsimulator\&.stack\&.Stack\&.pop () throws \fBEmptyException\fP, InterruptedException"

.PP
Definition at line 51 of file Stack\&.java\&.
.SS "void financialmarketsimulator\&.stack\&.Stack\&.push (\fBMarketEntryAttemptNode\fPnode) throws InterruptedException"

.PP
Definition at line 27 of file Stack\&.java\&.
.SS "\fBMarketEntryAttemptNode\fP financialmarketsimulator\&.stack\&.Stack\&.tryPop () throws \fBEmptyException\fP\fC [protected]\fP"

.PP
Definition at line 37 of file Stack\&.java\&.
.SS "boolean financialmarketsimulator\&.stack\&.Stack\&.tryPush (\fBMarketEntryAttemptNode\fPnode)\fC [protected]\fP"

.PP
Definition at line 21 of file Stack\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
