.TH "MarketManagerUnitTest" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MarketManagerUnitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBinstantiation\fP ()"
.br
.ti -1c
.RI "void \fBacceptBidTest\fP ()"
.br
.ti -1c
.RI "void \fBacceptOfferTest\fP ()"
.br
.ti -1c
.RI "void \fBremoveBidTest\fP ()"
.br
.ti -1c
.RI "void \fBremoveOfferTest\fP ()"
.br
.ti -1c
.RI "void \fBupdateEngineTest\fP ()"
.br
.ti -1c
.RI "void \fBupdateEntitiesTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 22 of file MarketManagerUnitTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void MarketManagerUnitTest\&.acceptBidTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 63 of file MarketManagerUnitTest\&.java\&.
.SS "void MarketManagerUnitTest\&.acceptOfferTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 74 of file MarketManagerUnitTest\&.java\&.
.SS "void MarketManagerUnitTest\&.instantiation ()"
Tests if the MarketManager object instantiates as expected 
.PP
Definition at line 52 of file MarketManagerUnitTest\&.java\&.
.SS "void MarketManagerUnitTest\&.removeBidTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 85 of file MarketManagerUnitTest\&.java\&.
.SS "void MarketManagerUnitTest\&.removeOfferTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 96 of file MarketManagerUnitTest\&.java\&.
.SS "void MarketManagerUnitTest\&.updateEngineTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 107 of file MarketManagerUnitTest\&.java\&.
.SS "void MarketManagerUnitTest\&.updateEntitiesTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 115 of file MarketManagerUnitTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
