.TH "MarketStrategyUnitTest" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MarketStrategyUnitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBmakeOfferTest\fP ()"
.br
.ti -1c
.RI "void \fBmakeBidTest\fP ()"
.br
.ti -1c
.RI "void \fBretractBidTest\fP ()"
.br
.ti -1c
.RI "void \fBretractOfferTest\fP ()"
.br
.ti -1c
.RI "void \fBsetStrategyTest\fP ()"
.br
.ti -1c
.RI "void \fBsearchMarketEntryAttempt\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 18 of file MarketStrategyUnitTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void MarketStrategyUnitTest\&.makeBidTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 50 of file MarketStrategyUnitTest\&.java\&.
.SS "void MarketStrategyUnitTest\&.makeOfferTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 43 of file MarketStrategyUnitTest\&.java\&.
.SS "void MarketStrategyUnitTest\&.retractBidTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 57 of file MarketStrategyUnitTest\&.java\&.
.SS "void MarketStrategyUnitTest\&.retractOfferTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 65 of file MarketStrategyUnitTest\&.java\&.
.SS "void MarketStrategyUnitTest\&.searchMarketEntryAttempt ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 81 of file MarketStrategyUnitTest\&.java\&.
.SS "void MarketStrategyUnitTest\&.setStrategyTest ()"

.PP
\fBTodo\fP
.RS 4

.RE
.PP

.PP
Definition at line 73 of file MarketStrategyUnitTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
