.TH "MatchingEngineUnitTest" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatchingEngineUnitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchingEngineUnitTest\fP ()"
.br
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBinstantiation\fP ()"
.br
.ti -1c
.RI "void \fBtradeTest\fP ()"
.br
.ti -1c
.RI "void \fBupdateTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 23 of file MatchingEngineUnitTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MatchingEngineUnitTest\&.MatchingEngineUnitTest ()"

.PP
Definition at line 25 of file MatchingEngineUnitTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void MatchingEngineUnitTest\&.instantiation ()"

.PP
\fBTodo\fP
.RS 4
Tests if the MatchingEngine object instantiates as expected 
.RE
.PP

.PP
Definition at line 53 of file MatchingEngineUnitTest\&.java\&.
.SS "void MatchingEngineUnitTest\&.setUp ()"

.PP
Definition at line 37 of file MatchingEngineUnitTest\&.java\&.
.SS "static void MatchingEngineUnitTest\&.setUpClass ()\fC [static]\fP"

.PP
Definition at line 29 of file MatchingEngineUnitTest\&.java\&.
.SS "void MatchingEngineUnitTest\&.tearDown ()"

.PP
Definition at line 41 of file MatchingEngineUnitTest\&.java\&.
.SS "static void MatchingEngineUnitTest\&.tearDownClass ()\fC [static]\fP"

.PP
Definition at line 33 of file MatchingEngineUnitTest\&.java\&.
.SS "void MatchingEngineUnitTest\&.tradeTest ()"

.PP
\fBTodo\fP
.RS 4
Tests the MatchingEngine trade() function\&. Two cases are tested: Firstly, if the trade function will record a trade when an offer and a bid are explicitly made to match, and secondly if the trade function will record no trade when all bids and offers are made explicitly not to match\&. The function creates mock bid and offer stacks and populates them with mock bid and offer objects\&. Trade is then called on those stacks\&. 
.RE
.PP

.PP
Definition at line 68 of file MatchingEngineUnitTest\&.java\&.
.SS "void MatchingEngineUnitTest\&.updateTest ()"

.PP
\fBTodo\fP
.RS 4
Observes the bid and offer stacks when called and informs the MarketManager to either update or not update the views accordingly\&. 
.RE
.PP

.PP
Definition at line 167 of file MatchingEngineUnitTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
