.TH "OfferUnitTest" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OfferUnitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBinstantiation\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 18 of file OfferUnitTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void OfferUnitTest\&.instantiation ()"

.PP
\fBTodo\fP
.RS 4
Tests if the Offer object instantiates as expected 
.RE
.PP

.PP
Definition at line 43 of file OfferUnitTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
