.TH "OfferUnitTest" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OfferUnitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOfferUnitTest\fP ()"
.br
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBinstantiation\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 18 of file OfferUnitTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OfferUnitTest\&.OfferUnitTest ()"

.PP
Definition at line 20 of file OfferUnitTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void OfferUnitTest\&.instantiation ()"

.PP
\fBTodo\fP
.RS 4
Tests if the Offer object instantiates as expected 
.RE
.PP

.PP
Definition at line 43 of file OfferUnitTest\&.java\&.
.SS "void OfferUnitTest\&.setUp ()"

.PP
Definition at line 32 of file OfferUnitTest\&.java\&.
.SS "static void OfferUnitTest\&.setUpClass ()\fC [static]\fP"

.PP
Definition at line 24 of file OfferUnitTest\&.java\&.
.SS "void OfferUnitTest\&.tearDown ()"

.PP
Definition at line 36 of file OfferUnitTest\&.java\&.
.SS "static void OfferUnitTest\&.tearDownClass ()\fC [static]\fP"

.PP
Definition at line 28 of file OfferUnitTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
