.TH "stackPackageUnitTests.MarketEntryAttemptNodeUnitTest" 3 "Fri Jun 27 2014" "Financial_Market_Simulato_ Documentation_V0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stackPackageUnitTests.MarketEntryAttemptNodeUnitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarketEntryAttemptNodeUnitTest\fP ()"
.br
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetUpClass\fP ()"
.br
.ti -1c
.RI "static void \fBtearDownClass\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Madimetja 
.RE
.PP

.PP
Definition at line 20 of file MarketEntryAttemptNodeUnitTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "stackPackageUnitTests\&.MarketEntryAttemptNodeUnitTest\&.MarketEntryAttemptNodeUnitTest ()"

.PP
Definition at line 22 of file MarketEntryAttemptNodeUnitTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void stackPackageUnitTests\&.MarketEntryAttemptNodeUnitTest\&.setUp ()"

.PP
Definition at line 34 of file MarketEntryAttemptNodeUnitTest\&.java\&.
.SS "static void stackPackageUnitTests\&.MarketEntryAttemptNodeUnitTest\&.setUpClass ()\fC [static]\fP"

.PP
Definition at line 26 of file MarketEntryAttemptNodeUnitTest\&.java\&.
.SS "void stackPackageUnitTests\&.MarketEntryAttemptNodeUnitTest\&.tearDown ()"

.PP
Definition at line 38 of file MarketEntryAttemptNodeUnitTest\&.java\&.
.SS "static void stackPackageUnitTests\&.MarketEntryAttemptNodeUnitTest\&.tearDownClass ()\fC [static]\fP"

.PP
Definition at line 30 of file MarketEntryAttemptNodeUnitTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Financial_Market_Simulato_ Documentation_V0\&.1 from the source code\&.
