.TH "todo" 3 "Fri Jun 27 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBBidUnitTest\&.instantiation\fP ()\fP" 1c
Tests if the Bid object instantiates as expected  
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketEntryAttempt\&.MarketEntryAttempt\fP (double pr, int numShares, String name)\fP" 1c
MarketEntryAttempt class constructor 
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketEntryAttempt\&.setNumberOfShares\fP (int _numShares)\fP" 1c
Sets the number of shares for the entry attempt, i\&.e\&. the number of shares being offered or bid 
.PP
\fBParameters:\fP
.RS 4
\fI_numShares\fP The number of shares for the entry attempt\&.  
.RE
.PP
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketEntryAttempt\&.setParticipantName\fP (String _name)\fP" 1c
Sets the name of the participant making the entry attempt\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_name\fP The name of the participant making the entry attempt\&.  
.RE
.PP
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketEntryAttempt\&.setPrice\fP (double _price)\fP" 1c
Sets the price of the shares for entry attempt, i\&.e\&. sets the price of shares being offered or bid\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_price\fP The price of the shares for the entry attempt\&.  
.RE
.PP
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketManager\&.acceptBid\fP (Bid bid)\fP" 1c
Acknowledgement of the bid being accepted by the market manager 
.PP
\fBParameters:\fP
.RS 4
\fIbid\fP Bid object to be accepted 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns a receipt object that acknowledges that a bid was accepted  
.RE
.PP
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketManager\&.acceptOffer\fP (Offer offer)\fP" 1c
Acknowledgement of the offer being accepted by the market manager 
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketManager\&.removeBid\fP (Bid bid)\fP" 1c
Acknowledgement of the bid being removed by the market manager 
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketManager\&.removeOffer\fP (Offer offer)\fP" 1c
Acknowledgement of the offer being removed by the market manager 
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketManager\&.updateEngine\fP ()\fP" 1c
Update the engine with the current states of the bid and offer stack\&.  
.IP "\fBMember \fBfinancialmarketsimulator\&.MarketManager\&.updateEntities\fP ()\fP" 1c
Update entities  
.IP "\fBMember \fBfinancialmarketsimulator\&.Trade\&.makeBid\fP ()\fP" 1c
Make a bid 
.IP "\fBMember \fBfinancialmarketsimulator\&.Trade\&.makeOffer\fP ()\fP" 1c
Make an offer 
.IP "\fBMember \fBfinancialmarketsimulator\&.Trade\&.retractBid\fP ()\fP" 1c
Retract a bid that was previously accepted 
.IP "\fBMember \fBfinancialmarketsimulator\&.Trade\&.retractOffer\fP ()\fP" 1c
Retract an offer that was previously accepted  
.IP "\fBMember \fBfinancialmarketsimulator\&.Trade\&.searchMarketEntryAttempt\fP (MarketEntryAttempt entry)\fP" 1c
Search for a market entry attempt (bid or offer) 
.IP "\fBMember \fBfinancialmarketsimulator\&.Trade\&.setStrategy\fP (String strategy)\fP" 1c
Set the current strategy of the participant 
.IP "\fBMember \fBMarketManagerUnitTest\&.acceptBidTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketManagerUnitTest\&.acceptOfferTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketManagerUnitTest\&.removeBidTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketManagerUnitTest\&.removeOfferTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketManagerUnitTest\&.updateEngineTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketManagerUnitTest\&.updateEntitiesTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketStrategyUnitTest\&.makeBidTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketStrategyUnitTest\&.makeOfferTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketStrategyUnitTest\&.retractBidTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketStrategyUnitTest\&.retractOfferTest\fP ()\fP" 1c
.IP "\fBMember \fBMarketStrategyUnitTest\&.searchMarketEntryAttempt\fP ()\fP" 1c
.IP "\fBMember \fBMarketStrategyUnitTest\&.setStrategyTest\fP ()\fP" 1c
.IP "\fBMember \fBMatchingEngineUnitTest\&.instantiation\fP ()\fP" 1c
Tests if the MatchingEngine object instantiates as expected  
.IP "\fBMember \fBMatchingEngineUnitTest\&.tradeTest\fP ()\fP" 1c
Tests the MatchingEngine trade() function\&. Two cases are tested: Firstly, if the trade function will record a trade when an offer and a bid are explicitly made to match, and secondly if the trade function will record no trade when all bids and offers are made explicitly not to match\&. The function creates mock bid and offer stacks and populates them with mock bid and offer objects\&. Trade is then called on those stacks\&.  
.IP "\fBMember \fBMatchingEngineUnitTest\&.updateTest\fP ()\fP" 1c
Observes the bid and offer stacks when called and informs the MarketManager to either update or not update the views accordingly\&.  
.IP "\fBMember \fBOfferUnitTest\&.instantiation\fP ()\fP" 1c
Tests if the Offer object instantiates as expected  
.IP "\fBMember \fBReceiptUnitTest\&.instantiation\fP ()\fP" 1c
Tests if the Receipt object instantiates as expected 
.PP

